import os

os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

ADFS_CLIENT_ID = os.environ.get("ADFS_CLIENT_ID")
ADFS_CLIENT_SECRET = os.environ.get("ADFS_CLIENT_SECRET")
ADFS_AUTHORITY = os.environ.get("ADFS_AUTHORITY")
ADFS_REDIRECT_URI = os.environ.get("ADFS_REDIRECT_URI")
ADFS_AUTHORIZE_ENDPOINT = os.environ.get("ADFS_AUTHORIZE_ENDPOINT")
ADFS_TOKEN_ENDPOINT = os.environ.get("ADFS_TOKEN_ENDPOINT")
ADFS_PROFILE_INFO = os.environ.get("ADFS_PROFILE_INFO")
ADFS_SIGNOUT_URL = os.environ.get("ADFS_SIGNOUT_URL")